// <auto-generated />
namespace PhamThiLoan_03.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Create_Table_PhongBan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_Table_PhongBan));
        
        string IMigrationMetadata.Id
        {
            get { return "202106060811014_Create_Table_PhongBan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
